### PR TITLE
Support Django 3

### PR DESCRIPTION
**Pull request by wlonk**
I've tested this locally via tox and it's good. I also read through the [3.0 backwards incompatible changes](https://docs.djangoproject.com/en/3.0/releases/3.0/#backwards-incompatible-3-0) and nothing should impact this library.

### CODE REVIEW

**Comment by wlonk** [comment]
@davisagli I'd love a merge on this when you get a chance.

**Comment by davisagli** [comment]
Looks good but can you update the CircleCI configuration to run with Django 3 also?

**Comment by wlonk** [comment]
Haha, I spotted that too! Just fixed it.

**Comment by davisagli** [comment]
@wlonk I don't see any problem with dropping Python 3.6 while we're at it.

**Comment by wlonk** [comment]
Making that change, stand by.

**Comment by wlonk** [comment]
Once this is merged, if we make a new release I can test out Django 3 on MetaShare.

**Comment by davisagli** [comment]
@wlonk can you trigger a build on oddbird's CircleCI? That should update the commit statuses on this pull request so I can merge. SFDO-Tooling's CircleCI is configured to not run builds for pull requests coming from another github organization.

**Comment by wlonk** [comment]
Ah, I was wondering what was stuck.

**Pull request merged**
